version: 2 # use CircleCI 2.0
jobs:
  node10:
    working_directory: ~/site
    docker: # run the steps with Docker
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "blog/package.json" }}
      - run:
          name: Install Deps
          command: cd blog && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "blog/package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Test
          command: cd blog && npm test
      - run: # run linter
          name: Lint
          command: cd blog && npm run lint
  node8:
    working_directory: ~/site
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "blog/package.json" }}
      - run:
          name: Install Deps
          command: cd blog && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "blog/package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Test
          command: cd blog && npm test
      - run: # run linter
          name: Lint
          command: cd blog && npm run lint
  lts:
    working_directory: ~/site
    docker: # run the steps with Docker
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "blog/package.json" }}
      - run:
          name: Install Deps
          command: cd blog && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "blog/package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Test
          command: cd blog && npm test
      - run: # run linter
          name: Lint
          command: cd blog && npm run lint

workflows:
  version: 2
  test_versions:
    jobs:
      - node10
      - node8
      - lts